version: '3'

volumes:
  db-store:
  db-test-store:

services:
  proxy:
    container_name: proxy
    build: ./docker/nginx
    ports:
      - '8000:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./back:/usr/share/nginx/html
  
  back:
    container_name: back
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/php/php.ini
      - ./back:/var/www/html

  front:
    container_name: front
    build: ./docker/front
    tty: true
    volumes:
      - ./front:/data/src
    ports:
      - "5173:5173"

  db:
    container_name: db
    build: ./docker/mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - db-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: phper
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

  db-test:
    container_name: db-test
    build: ./docker/mysql
    ports:
      - 3000:3306
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - db-test-store:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_db_test
      MYSQL_USER: phper
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

  mail:
    container_name: mailpit
    build: ./docker/mail
    ports:
      - 8025:8025
      - 1025:1025
